const express = require('express')
const path = require('path');
// Tạo phiên bản nhanh
const app = express()

// Yêu cầu các tuyến API
const autosearch = require('./routes/autosearch')
const goiyhomnay = require('./routes/goiyhomnay')
const search = require('./routes/search')
const product = require('./routes/product')
const nhanxet = require('./routes/nhanxet')
const shop = require('./routes/shop')
const searchmap = require('./routes/searchmap')
const mapapi = require('./routes/mapapi')
const login = require('./routes/login')
const authlogin = require('./routes/authlogin')
const donhang = require('./routes/donhang')
const uploadimgdaidien = require('./routes/uploadimgdaidien')

const thongbao = require('./routes/thongbao')
const thongbaodadoc = require('./routes/thongbaodadoc')
const thongbaotoken = require('./routes/thongbaotoken')
const thongbaomuadh = require('./routes/thongbaomuadh')

const donhangcuatoi = require('./routes/donhangcuatoi')
const donhanghuy = require('./routes/donhanghuy')
const dangxuat = require('./routes/dangxuat')
const danhgia = require('./routes/danhgia')
const danhgianhanxet = require('./routes/danhgianhanxet')
const danhgiathanhcong = require('./routes/danhgiathanhcong')
const cuahangdh = require('./routes/cuahangdh')
const cuahangid = require('./routes/cuahangid')
const chitietdh = require('./routes/chitietdh')
const caidatshop = require('./routes/caidatshop')
const cuahangsp = require('./routes/cuahangsp')
const cuahangsuasp = require('./routes/cuahangsuasp')
const cuahangimgsp = require('./routes/cuahangimgsp')
const cuahangthaydoisp = require('./routes/cuahangthaydoisp')
const uploadimgsp = require('./routes/uploadimgsp')
const uploadimgspbe = require('./routes/uploadimgspbe')
const cuahangbaocao = require('./routes/cuahangbaocao')
const cuahangtraloi = require('./routes/cuahangtraloi')
const traloinx = require('./routes/traloinx')
const shipperdh = require('./routes/shipperdh')
const shippermap = require('./routes/shippermap')
const shipperxacnhan = require('./routes/shipperxacnhan')
const shipperxacnhandagiao = require('./routes/shipperxacnhandagiao')
const shipperxacnhanhuydon = require('./routes/shipperxacnhanhuydon')
const shipperbaocao = require('./routes/shipperbaocao')
const quanli = require('./routes/quanli')
const quanlithem = require('./routes/quanlithem')
const cuahangxacnhan = require('./routes/cuahangxacnhan')
const chat = require('./routes/chat')
const chatnd = require('./routes/chatnd')
const facebookdh = require('./routes/facebookdh')
const facebookdhgui = require('./routes/facebookdhgui')



// Nhập các tuyến API
app.use(autosearch)
app.use(goiyhomnay)
app.use(search)
app.use(product)
app.use(nhanxet)
app.use(shop)
app.use(searchmap)
app.use(mapapi)
app.use(login)
app.use(authlogin)
app.use(donhang)
app.use(uploadimgdaidien)
app.use(thongbao)
app.use(thongbaodadoc)
app.use(donhangcuatoi)
app.use(donhanghuy)
app.use(dangxuat)
app.use(danhgia)
app.use(danhgianhanxet)
app.use(danhgiathanhcong)
app.use(cuahangdh)
app.use(cuahangid)
app.use(chitietdh)
app.use(caidatshop)
app.use(cuahangsp)
app.use(cuahangsuasp)
app.use(cuahangimgsp)
app.use(cuahangthaydoisp)
app.use(uploadimgsp)
app.use(uploadimgspbe)
app.use(cuahangbaocao)
app.use(cuahangtraloi)
app.use(traloinx)
app.use(shipperdh)
app.use(shippermap)
app.use(shipperxacnhan)
app.use(shipperxacnhandagiao)
app.use(shipperxacnhanhuydon)
app.use(shipperbaocao)
app.use(quanli)
app.use(quanlithem)
app.use(cuahangxacnhan)
app.use(chat)
app.use(chatnd)
app.use(thongbaotoken)
app.use(thongbaomuadh)
app.use(facebookdh)
app.use(facebookdhgui)
app.use(express.static(path.join(__dirname, '/public')))

// Xuất ứng dụng nhanh
module.exports = app

// Khởi động máy chủ độc lập nếu đang chạy trực tiếp
// if (require.main === module) {
//   const port = process.env.PORT || 3000
//   app.listen(port, () => { })
// }